# version: "3.8"

# services:
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend:/app
#     environment:
#       - FLASK_ENV=development

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#     environment:
#       - NODE_ENV=development






version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/frontend/build
    environment:
      - FLASK_ENV=development
    command: python app.py

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
